# Generated by Django 5.2.4 on 2025-07-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tvshow_first_air_date_tvshow_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='first_air_date',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='id',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='name',
            field=models.CharField(default='Untitled Show'),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='origin_country',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='original_language',
            field=models.CharField(null=True),
        ),
    ]
