# Generated by Django 5.2.4 on 2025-07-15 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tvshow_slug_alter_tvshow_first_air_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('overview', models.TextField(null=True)),
                ('name', models.CharField(null=True)),
                ('season_number', models.IntegerField()),
                ('episode_number', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tvshow',
            name='number_of_episodes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tvshow',
            name='number_of_seasons',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('department', models.CharField()),
                ('job', models.CharField()),
                ('credit_id', models.CharField()),
                ('name', models.CharField()),
                ('profile_path', models.CharField()),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.crew')),
            ],
        ),
        migrations.AddField(
            model_name='crew',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew', to='api.episode'),
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('character', models.CharField()),
                ('name', models.CharField()),
                ('profile_path', models.CharField()),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='api.episode')),
            ],
        ),
        migrations.CreateModel(
            name='GuestStars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_stars', to='api.episode')),
            ],
        ),
        migrations.CreateModel(
            name='TvSeason',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('overview', models.TextField(null=True)),
                ('name', models.CharField(null=True)),
                ('poster_path', models.CharField(null=True)),
                ('season_number', models.IntegerField()),
                ('vote_average', models.IntegerField()),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='api.tvshow')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='api.tvseason'),
        ),
    ]
