# Generated by Django 5.2.4 on 2025-07-26 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_crew_episode_tvshow_number_of_episodes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crewmember',
            name='fk',
        ),
        migrations.RemoveField(
            model_name='gueststars',
            name='fk',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='fk',
            new_name='season',
        ),
        migrations.RenameField(
            model_name='tvseason',
            old_name='fk',
            new_name='show',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='fk',
        ),
        migrations.AddField(
            model_name='episode',
            name='crewmembers',
            field=models.ManyToManyField(related_name='episodes', to='api.crewmember'),
        ),
        migrations.AddField(
            model_name='episode',
            name='guests',
            field=models.ManyToManyField(related_name='episodes', to='api.guest'),
        ),
        migrations.CreateModel(
            name='WatchedEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(null=True)),
                ('review_comment', models.TextField(null=True)),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_by', to='api.episode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'episode')},
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_watchlists', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'episode')},
            },
        ),
        migrations.DeleteModel(
            name='Crew',
        ),
        migrations.DeleteModel(
            name='GuestStars',
        ),
    ]
